ALTER TABLE camera ADD COLUMN issues INTEGER NOT NULL DEFAULT 0;
ALTER TABLE camera ADD COLUMN wifi_signal INTEGER NOT NULL DEFAULT 0;
ALTER TABLE camera ADD COLUMN lfr_signal INTEGER NOT NULL DEFAULT 0;
ALTER TABLE syncmodule ADD COLUMN last_hb TEXT;